### ISSUE TITLE
How to make branch tip names and tip pies align with branches?

### ISSUE THREAD

**Issue by NiklasDreyer** [stevenheritage/MBASR#2]
Dear Steven,

Thanks for building MBARS. It is indeed super easy, user-friendly and looks stunning. 

I am watching the MacOS tutorial (https://www.youtube.com/watch?v=-yfvz2SJp5o&ab_channel=DukeDFP) and find that tree and the annotation quite pretty. However, when I run my analysis and plot the tree, the species names and tip pies are not attached to/aligned with the branch tips. This makes the annotation quite chaotic.

My figure can be viewed here: https://drive.google.com/file/d/14uzIlV71PgdA5iy5ukYdpZvgAzSdqOC5/view?usp=sharing

Can you recommend some plot settings that allow me to align tip pies and branch tip names (species names) to the branches? 

Best,
Niklas Dreyer

These are my plot settings:

my.plot.width=10
my.plot.height=12.5
my.tree.edge.width=0.5
my.tip.label.font.size=0.4
my.tip.label.offset=1.00
my.node.pie.size=0.20
my.node.pie.border.width=0.05
my.tip.pie.size=0.15
my.tip.pie.border.width=0.05
my.tip.pie.offset=1.00
my.legend.size=0.5
my.legend.shift.up=1.5 
show.node.numbers=FALSE
show.time.scale=FALSE
my.time.scale.youngest.tip=0
my.time.scale.bar.shift.up=-1
my.time.scale.label.shift.up=6.75

**Comment by stevenheritage** [comment]
Hi Niklas,

I can certainly help with this. Can you please send me your Newick format tree (input) and MrBayes.ASR.results.txt (results) files? As attachments directly to my email ***@***.***).

Cheers,
Steven

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
