### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by pwkooij** [stevenheritage/MBASR#7]
Just a quick question, has this been tested on a Linux OS?

**Comment by stevenheritage** [comment]
Hi Pepijn,
Thanks for this question. I have tried MBASR with Ubuntu, and it will not work. If I recall correctly, the issues have to do with how R behaves under that operating system. Very sorry.
All my best, Steven

**Comment by pwkooij** [comment]
Ok! That's a shame, but good to know!
